name: CI

on:
  pull_request:
  push:
    branches: [develop]

permissions:
  contents: read

jobs:
  ci:
    uses: pilgrimagesoftware/github-actions/.github/workflows/rust-ci.yaml@master
    with:
      test-args: "--all-features --workspace"
      no-default-features-test: true
      doc-test: true
      doc-build: true
