name: Prepare Release

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  prepare:
    uses: pilgrimagesoftware/github-actions/.github/workflows/rust-prepare-release.yaml@master
    with:
      project-number: 9
    secrets: inherit
